[pytest]
# Ignore Unknown Mark Warnings
filterwarnings=
     ignore::pytest.PytestUnknownMarkWarning

# Look for tests in the tests directory
testpaths = tests

# Console output settings
log_cli = true
log_cli_level = INFO


bdd_features_base_dir = .
