name: Titan Framework CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  titan-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "WC_KEY=${{ secrets.WC_KEY }}" >> .env
          echo "WC_SECRET=${{ secrets.WC_SECRET }}" >> .env

      - name: Run Tests via Docker Compose
        run: |
          docker compose up --build --abort-on-container-exit --exit-code-from tests

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure_reports
          path: allure_reports/
          retention-days: 7